sudo: required
dist: trusty
group: deprecated-2017Q4
language: csharp
solution: ExpediaInterview.sln
mono: none
dotnet: 2.1.2
script:
- dotnet restore
- cd ExpediaInterviewUnitTests
- dotnet test
deploy:
  provider: heroku
  buildpack: "https://github.com/jincod/dotnetcore-buildpack"
  api_key:
    secure: pJhfCt1q+/uMJVm0zY3WuW/WRJI8JnxUcGC0vLgbxYCm4TdRlTd88+D7P88KO6mJ5FuHP8GedCQg5RhcwCHb2+vdhPDhTnqYDD/+qpYgPdgFnKC2ScbmyfcbW4FM4eVf+rdvn9bt7ndtQioqTzHyDkf/Ho8Qpwiejuqo5SWx6M/yxShimb+5ALbeeq016SKT8zgoClOJ6NfrhmGu6XNG8h1pvBSMXJHFeDOrx/IG0AHsfKixWn5dZm28eUEh+/pu1I6oKt1ATl7hrClpnWK5Zi888mnNl2WOr6iI9Y6x+npiMymUzO03GNS/qcr9BOm1Caeexg59OT7eiBkxV1wif799Kj0TVQ7NQxyRqwPHL83pbHo18+3GqO4/Fer1OGnr+fVXDiephqt2H89QnhnMmeDT0bOpD/GVozLNuNti8DK51P0thbXhPP3uHN3EHewTS0QWGHr8yFCN44lLsnqU9+3zkl3KOJmcqBRPG9Q68IUzzwTQxEHQTdyMpcmZTnqmNVSw2OIOf2CHelYtlo8zmhPqD26sNcbGa5bqiEqbvxG4hhPndn1Qmu9os+BfaD6kTZ/uun3L0nxbwXIEH+oltFjY17LOwRd6l94yhPdXAc1Zb+8i+1Vrd47esdxBP3/8El6G8qnvYj5BoMZiQAkZUxMZDuRXtuhGwDSmmckYdNc=
  app: xpsdealsfinder
  strategy: git
  skip_cleanup: true
  on:
    repo: a-ayyash/xpsdeals
